### ISSUE TITLE
Animbits: New anim gpu cache manager

### ISSUE THREAD

**Issue by jdrese** [mgear-dev/animbits#11]
# Anim cache manager

The animation GPU cache manager is a simple animation tool that allows animators to create a GPU cache representation of their rigs in the scene

## Key points
* caching can be generated either in temp folder or workspace folder or custom
* caching destination settings need to be stored (we can as well create a Maya env variable to override the destination folders for those who might need it inside a pipeline)
* file name is going to be based on the asset namespace name + file scene + artist name or something like that
* list of rig assets need to be searchable
* There is a limitation with GPU cache in terms of shading so we need to use something to bake the shading into vertex color on the GPU cache so that the representation is closer to the viewport
* The tool need to give the option to users to point out a group name of selection set that contains the rig meshes to be baked into GPU. Maybe this can be as well be overwritten by an env variable
- [x] Add rig query ENV VAR
- [x] Add rig queries
- [x] Add cache destination ENV VAR
- [x] Add cache destination preferences files
- [x] Handle color vertex shading transfer
- [x] GPU generation
- [x] Rig switch on ref or non ref
- [x] UI design
- [x] ListModel, ListView
- [x] Add Model group ENV VAR
- [x] Generate preference folder
- [x] Generate preference file
- [x] Generate preference file content
- [x] Rig switch
- [x] Store rigs in scene in a different way as the current will cause issues in certain cases
- [x] Add delete all gpu caches
- [x] Add color feedback when rig is unloaded
- [x] Change options widget for a collapsable one
- [x] Add plugin check when loading cache
- [x] Add shader override for incompatible shaders
- [x] Try managind hiding rig method even if visibility attribute is locked or connected or both
- [x] Fix doubles in list

**Comment by miquelcampos** [comment]
@jdrese  thanks for this!  
The specifications looks perfect!

**Comment by jdrese** [comment]
Thanks for the title @miquelcampos  forgot about that :P

**Comment by jdrese** [comment]
Hello @miquelcampos 

I've merged the first version into master so you can give it a shot.
The things that are on the task list are still to do but I will create separate tickets for those after your feedback to close this issue and the branch as well.  Let me know.

Cheers

**Comment by miquelcampos** [comment]
Hi @jdrese  I will check it today and deploy a beta version inside the studio to test with production assets. I will let you know ASAP how is going :) Thanks!

**Comment by miquelcampos** [comment]
@jdrese 

Is a little thing but, We need to add a check and auto-load for the gpuCache Plugin
```# Warning: Unknown object type: gpuCache #```

**Comment by jdrese** [comment]
You are correct. This check was only added when generating the cache but forgot to add it as well when reading the caches
