### ISSUE TITLE
Channel Master: Alternative Maya's channel box

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/animbits#14]
Channel box alternative 

- [x] custom channel list configurations
- [x] color coding
- [x] easy keyframe icons and functions (like softimage)
- [x] slider precision options (like houdini)
- [x] quick filter/search
- [x] not need to have the object selected to have an active channel list
- [ ] option to controls the Channel Master widget transparency. 

Some inspirational references:

Naughty Dog

![image](https://user-images.githubusercontent.com/1050212/70024505-a5182480-15dd-11ea-8cce-b5bcbdf4e32a.png)

https://youtu.be/oGDIMftV4ng?t=2797

Softimage Keying panel
![image](https://user-images.githubusercontent.com/1050212/70024440-6edaa500-15dd-11ea-9a63-5567fdf85f10.png)

**Comment by miquelcampos** [comment]
XSI right click menu ref
![image](https://user-images.githubusercontent.com/1050212/73819969-05248480-4834-11ea-9062-446b5d0f291f.png)
Icons color coding
![image](https://user-images.githubusercontent.com/1050212/73820009-18375480-4834-11ea-9cc6-6511504c8f85.png)

**Comment by miquelcampos** [comment]
![image](https://user-images.githubusercontent.com/1050212/74514152-5d076d80-4f4f-11ea-846b-7cf473fb9159.png)


- [ ] Callbacks for sync. Deactivate when playback or scrolling time
- [ ] Configuration needs to be persistent in the scene
- [ ] Also Export/import configuration
- [ ] Selected channels and middle-click scroll in the 3d view should function as default channel box

**Comment by jdrese** [comment]
This seems nice @miquelcampos 
It might worth creating a css stylesheet for this gui as well so that we can give it a controlled display... I could actually build color themes as well on this...

**Comment by miquelcampos** [comment]
@jdrese  I will check on that.

**Comment by miquelcampos** [comment]
here is a little WIP image using Pyflow widgets.  
![image](https://user-images.githubusercontent.com/1050212/74645976-46b21980-51bc-11ea-9c78-8ea03048ac3e.png)

@jdrese these widgets already work with CSS style :D

**Comment by jdrese** [comment]
This is so cool @miquelcampos 

Definitely going to be a super useful add. Maya's channelbox is rudimentary in some ways. The do have the precision incremental values thing but the readability of it all is quite bad.

**Comment by miquelcampos** [comment]
WIP image
![image](https://user-images.githubusercontent.com/1050212/75666756-bd214200-5cb9-11ea-8649-609607f53516.png)

**Comment by jdrese** [comment]
The slider is then in a different box than the typing value right? In Maya they are both in the sale box. Could by nice (preference wise) to be able to hide the sliders. What do you think?

**Comment by miquelcampos** [comment]
Nop it is in the same box. it is a widget from pyflow

But yep hide the slider can be a cool addition :)

**Comment by miquelcampos** [comment]
@jdrese I think just by setting a minimum width will work like expected
![collapse sliders](https://user-images.githubusercontent.com/1050212/75736992-0e751400-5d42-11ea-863c-25b1cb0ce97b.gif)

**Comment by jdrese** [comment]
@miquelcampos that is great !

**Comment by miquelcampos** [comment]
another WIP Gif
![channel_master_wip_01](https://user-images.githubusercontent.com/1050212/75852500-78b7b280-5e2f-11ea-9ece-8ff4f3c3e7d4.gif)

**Comment by jdrese** [comment]
Nice I really like it @miquelcampos. 👏 
Good addition the open source icons. 👍 
From what I see on the gif I have one single comment and that would be that I am not a huge fan of the copy/paste top bottom layout on those buttons. I know this is purely personal. It is just that menu bars have more often their layout been horizontal and not vertical. The +/- buttons make more sense to me as you place them. I would say as well that the borders on the big menu box thingy (don't know what it is)  are too round. It visually clashes with the buttons on the side. Again this is purely subjective.

**Comment by miquelcampos** [comment]
@jdrese thanks for the feedback

I have removed the round corners.   The big box is just a search box. I did it bigger to fill the space
![channel_master_wip_02](https://user-images.githubusercontent.com/1050212/75860429-2a121480-5e3f-11ea-8e76-4f1b576cba94.gif)
about the copy-paste icons. I kind of like it like that to keep everything compact. 
![image](https://user-images.githubusercontent.com/1050212/75860536-54fc6880-5e3f-11ea-9342-75083312a050.png)
I think these 2 buttons will be used less. But still want to add it to the UI.

this is a little inspired in Softimage UI design
![image](https://user-images.githubusercontent.com/1050212/75860791-c0ded100-5e3f-11ea-8812-a9c5a8651fb8.png)

**Comment by jdrese** [comment]
Okay I see what you are going for. What are the +/- buttons for?
Due to the size of the icons I would recommend putting the search bar bellow or above the buttons layout and make it thinner.  What I find visually bothering is the fact that the horizontal line gets cluttered with the lock and reload/cycle buttons.

Promise I will stop now 😃 bothering you with UI stuff. I am not an expert on this matter. Exited of checking this one out.

**Comment by miquelcampos** [comment]
@jdrese  the +/- buttons are to add channels from other controls. This will allow creating configurations/ combinations of channels from different objects.

I will think more about the layout arrangement. :)  
Thanks for the feedback!

**Comment by miquelcampos** [comment]
@jdrese here is a quick re-arrange

![image](https://user-images.githubusercontent.com/1050212/75869055-5ed89880-5e4c-11ea-92f6-e8c704b00b52.png)
Still thinking about it :P

**Comment by miquelcampos** [comment]
another option:
![image](https://user-images.githubusercontent.com/1050212/75869826-7e23f580-5e4d-11ea-80b8-17fc288aed5a.png)

**Comment by jdrese** [comment]
I like the last one better for sure as the search bar clutters less the view now and you have more space for the buttons. If you are not adding new buttons to fill the hole that you now have I would recommend just using some passing in between them (horizontally) to fill the space evenly and this spacing reduces the margin of miss-clicks specially when you are using a tablet or touch device...

**Comment by miquelcampos** [comment]
@jdrese  good point, 
![image](https://user-images.githubusercontent.com/1050212/75872754-158b4780-5e52-11ea-9453-bca1ede0b8bf.png)
but...  when it is very small 
![image](https://user-images.githubusercontent.com/1050212/75872826-35bb0680-5e52-11ea-909f-adcd45b5bb10.png)

**Comment by jdrese** [comment]
The one on the right seems good no? You can still try to drive the icon size depending on the UI with size but I think that is not fully necessarily. As long as on the "default" type of size things are readable and tight then it's up to the user to set the size they want. When it comes to responsible UI's like on webdesign Qt is not make for this type of things unfortunately.

**Comment by miquelcampos** [comment]
@jdrese after a few tests I think I have one that I like
![image](https://user-images.githubusercontent.com/1050212/75875021-3eadd700-5e56-11ea-8140-a140c547362e.png)


I will keep it for the moment and maybe review later when the tool is close to finish :)

**Comment by jdrese** [comment]
HAhaha, now I feel bad about myself making you go all that way. I'll let myself out 🚶...

**Comment by miquelcampos** [comment]
The notes in this ticket are now split in a different ticket to track better all the progress and commits
