### ISSUE TITLE
Channel Master: NODE

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/animbits#15]
this node will store the channel master configuration data inside the scene. 

- This includes the different tabs
- Should be possible to export and import this data

**Comment by miquelcampos** [comment]
support for multiple nodes???

![image](https://user-images.githubusercontent.com/1050212/75870542-6b5df080-5e4e-11ea-9bb7-508da7d6569b.png)

**Comment by jdrese** [comment]
The idea is been able to drive one or more controls that share attributes right?
The combo box would point to what? the node name to force single control or it's going to point to a config of nodes?

**Comment by miquelcampos** [comment]
not exactly. For the moment is just a not for myself. I will explain you later.  ;)
