### ISSUE TITLE
channel Master: Callbacks

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/animbits#19]
~~populate  channel values~~
~~update channel values~~
~~update values from channel~~
~~stop syn when playback or scroll timeline~~
~~stop hidden taps sync~~
~~store data when config change~~

**Comment by miquelcampos** [comment]
Maybe is better to update channels values in the Channel master when recovering focus?  
This will avoid a massive number of callbacks and possible slowdowns.

**Comment by jdrese** [comment]
I think it really depends on how you are handling this. You should only have one callback installed and that single one takes care of updating whatever matching control/channel is suppose to update no?

**Comment by miquelcampos** [comment]
I have been researching that. But for the moment what I have found is that the attribute should be provided when the callback is declared.  So that will force to create at less 1 callback for each object with 1 or more attributes tracked by the callback

The issue is that one of the main goal functionalities of this tool is to create and mix channel configuration, so can be channels from a different object in the same channel master tab.
So tracking all these channels callbacks looks complex and prone to errors.

For the moment I am working towards refreshing on demand, looks much more simple but also have caveats

**Comment by miquelcampos** [comment]
- [ ]  check undo stack when update attributes with channel master

**Comment by miquelcampos** [comment]
Looks like on-demand update works great. So for the moment, there is no need for any callback
